media: https://beingtechnicalwriter.s3.ap-south-1.amazonaws.com/
pagniagte: 10
output: web
timezone: Asia/Kolkata
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

algolia:
  application_id: "HSC1VAQ0SE"
  index_name: "BTW"
  search_only_api_key: "a2f6988f40ebadf013f3e4a75caf3fe3"
  nodes_to_index: 'p,.summary'

format: web

# Build settings

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

permalink: /:year/:month/:day/:title/
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      search: true
      author: <a href='/aboutme/'>Gaurav Trivedi</a>

exclude:
  - _drafts
  - _site

target: web

####### jekyll seo tag configuration #######
title: being technical writer
tagline: Only place where you learn about all the <strong>innovations</strong>, <strong>standards</strong>, and <strong>trends</strong> in technical writing.
description: This blog covers popular topics in technical writing.
url: "https://beingtechnicalwriter.com"
social:
  name: Gaurav Trivedi
  links:
    - https://www.linkedin.com/in/gauravtrivedi1988/
    - https://github.com/Trivedi-Gaurav

lang: en_US

