media: https://beingtechnicalwriter.s3.ap-south-1.amazonaws.com/
paginate: 10
output: web
timezone: Asia/Kolkata
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge


format: web

plugins:
  - jekyll-paginate


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
      comments: true
      search: true
      author: <a href='/aboutme/'>Gaurav Trivedi</a>
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      comments: true
      search: true

exclude:
  - _drafts
  - _site

target: web

####### jekyll seo tag configuration #######
title: being technical writer
tagline: A technical writing blog that offers tutorials, events, podcasts, latest trends, and other topics in the field of technical writing.
description: This blog covers popular topics in technical writing.
url: "https://beingtechnicalwriter.com"
author:
  twitter: TGaurav88
twitter:
  username: TGaurav88
  card: summary

logo: https://beingtechnicalwriter.s3.ap-south-1.amazonaws.com/logo/btwlogo.png

social:
  name: Gaurav Trivedi
  links:
    - https://twitter.com/TGaurav88
    - https://www.linkedin.com/in/gauravtrivedi1988/
    - https://github.com/Trivedi-Gaurav

lang: en_US

