media: https://adarsh-bm12.github.io/adarsh.github.io/
pagniagte: 10
output: web
timezone: Asia/Kolkata
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

format: web

# Build settings

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

permalink: /:year/:month/:day/:title/
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
      comments: true
      search: true
      author: <a href='/aboutme/'>Adarsh BM</a>

exclude:
  - _drafts
  - _site

target: web

####### jekyll seo tag configuration #######
title: Adarsh BM
tagline: Only place where you learn about all the <strong>innovations</strong>, <strong>standards</strong>, and <strong>trends</strong> in technical writing.
description: Making technical writing easy
url: https://adarsh-bm12.github.io/adarsh.github.io
social:
  name: Gaurav Trivedi
  links:
    - https://www.linkedin.com/in/adarsh.bm/
    - https://github.com/adarsh.bm

lang: en_US

